on:
  push:
    branches:
    - '*'
    
permissions: 
  contents: write
  pull-requests: write

name: Build project
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'http://registry.npmjs.org'
         
      - name: Install Dependencies
        run: |
          npm i

      - name: Build 
        run: npm run build
